[build]
  command = "npm install && npm run build:vite"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--no-deprecation"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  command = "npm run dev:vite"
  autoLaunch = true

# Redirect all URL paths to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 