[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

# Redirect all URL paths to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 